from screeninfo import get_monitors

MAIN_COLOUR = "#393A3A"#black
FRAME_COLOUR = "#575959"#dark grey
CANVAS_COLOUR = "#F4F4F4"#white
LINE_COLOUR = "black"

MAIN_COLOUR_LABEL_BG = "#FF642F"#orange
MAIN_COLOUR_LABEL_TEXT = "black"
MAIN_COLOUR_BUTON_BG = "#F89344"#red

# monit_info = get_monitors()
# print(monit_info)
WINDOW_W = 1900#1000
WINDOW_H = 900#600

FRAME_SITUATION = 1/4
BORDERS_SPACE = 10

FRAME_W = WINDOW_W * FRAME_SITUATION - BORDERS_SPACE
FRAME_H = WINDOW_H - 2 * BORDERS_SPACE

CANVAS_SITUATION = 1 - FRAME_SITUATION
COLUMNS = 26

CANVAS_H = WINDOW_H - 2 * BORDERS_SPACE
CANVAS_W = WINDOW_W * CANVAS_SITUATION - 2 * BORDERS_SPACE